/**
 * Chat API SDK
 * The SDK allows you to receive and send messages through your WhatsApp account. [Sign up now](https://app.chat-api.com/)  The Chat API is based on the WhatsApp WEB protocol and excludes the ban both when using libraries from mgp25 and the like. Despite this, your account can be banned by anti-spam system WhatsApp after several clicking the \"block\" button.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sale@chat-api.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ReadChatStatus model module.
 * @module model/ReadChatStatus
 * @version 1.0.0
 */
class ReadChatStatus {
    /**
     * Constructs a new <code>ReadChatStatus</code>.
     * @alias module:model/ReadChatStatus
     */
    constructor() { 
        
        ReadChatStatus.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ReadChatStatus</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ReadChatStatus} obj Optional instance to populate.
     * @return {module:model/ReadChatStatus} The populated <code>ReadChatStatus</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ReadChatStatus();

            if (data.hasOwnProperty('read')) {
                obj['read'] = ApiClient.convertToType(data['read'], 'Boolean');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('chatId')) {
                obj['chatId'] = ApiClient.convertToType(data['chatId'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} read
 */
ReadChatStatus.prototype['read'] = undefined;

/**
 * Chat reading status
 * @member {String} message
 */
ReadChatStatus.prototype['message'] = undefined;

/**
 * @member {String} chatId
 */
ReadChatStatus.prototype['chatId'] = undefined;






export default ReadChatStatus;

